### ISSUE TITLE
Carrot ship Christmas version has missing transparency

### ISSUE THREAD

**Issue by vallenrod** [KScl/opentyrian2000#17] opened 2024-12-14 02:06 UTC
When Christmas mode is activated the Carrot Ship (green) has visible rectangle around it.

**Comment by vallenrod** [comment] 2024-12-14 02:09
![Screenshot 2024-12-13 210841](https://github.com/user-attachments/assets/b24581e8-f852-4ee9-8743-e2da7a5c5206)

**Comment by KScl** [comment] 2024-12-15 12:43
Duplicate of #8: This is not a bug, Tyrian 2000's data files contain this error.

**Closed as not planned by KScl** 2024-12-15 12:43 UTC
Labels: accurate to original game
