### ISSUE TITLE
Bug on Scaling Mode

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [KScl/opentyrian2000#9] opened 2023-10-16 22:05 UTC
When using "Scaling Mode: Fit to 8:5", Player 1 (or Player 2 in 2-player mode) moves slowly to the left permanently.

**Comment by KScl** [comment] 2023-11-12 05:52
Relevant issue/commit in mainline: opentyrian#34, 0206a17

This should get coincidentally fixed when I have the opportunity to rebase all the changes mainline did in the past year or so. I haven't had the time lately (and won't for this month due to an impending move), but I'll keep it in mind when everything settles down.

**Comment by KScl** [comment] 2024-02-18 23:31
Confirmed fixed by 132e8b4.

**Closed by KScl** 2024-02-18 23:31 UTC
Labels: bug, fixed in mainline
